import type { Metadata } from "next";
import "./globals.css";
// import "../src/globals.css"

export const metadata: Metadata = {
  title: "Amazon Web Scraper",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>

        {children}
        </main>
      </body>
    </html>
  );
}
